### ISSUE TITLE
Voters can receive notifications about a new Vote/Poll 

### ISSUE THREAD

**Issue by shw66** [dhkjhgjaih/Harvard-CSCI-S71-Team7#42]
## User Story:
***As a*** voter
***I want to*** receive a notification
***So that*** I know there is a new Poll waiting for my vote.
  
## Additional Details:
- Users should know about a new available Poll
- If user missed the email notification for example, once it enters the app, it should be visible for him about the new Poll available.
  
## Acceptance Criteria:
- When a new Vote/Poll is created and a user is invited, an email is sent to the user.
- When a new Vote/Poll is created but a user missed the email notification, when he visits the website he should see the Poll waiting for his vote.
- When the deadline for a new Vote/Poll is ending in 24 hours,  users should get a notification message/email to remind him to vote.
- When the deadline for a new Vote/Poll is ended,  users should get a notification message/email to remind him to view the results.

**Comment by nathanweeks** [comment]
Closed during sprint planning meeting
