### ISSUE TITLE
Setup Project minimal project infrastructure (Web Server, Database, CI/CD)

### ISSUE THREAD

**Issue by gugavaro** [dhkjhgjaih/Harvard-CSCI-S71-Team7#43]
## User Story:
***As a*** developer,
***I want to*** setup an environment on the cloud
***So that*** I can host my application, my database and my devops pipeline.
  
### As part of our project infrastructure setup, we will need to follow items:
- In order to be able to deploy our project we need to setup a Web Server either on Azure or AWS
- We should create a blob storage or a Sql Database to store our application data
- A continuous development/continuous deployment pipeline to easily test and deploy our app.
  
## Acceptance Criteria:
- We are able to run our app from a public endpoint
- Our app can store and retrieve data
- We are able to run a CI/CD pipeline as part of our dev-loop, new app should not be deployed in case os test failures.

**Comment by nathanweeks** [comment]
merged with #4

**Comment by nathanweeks** [comment]
Merged with #4
